### ISSUE TITLE
Disassembling SMAHO without destroying it

### ISSUE THREAD

**Issue by rreihert** [Sinclair81/Homebridge-Tasmota-TS#2]
Hi Mario,

can you write a little something about how you got the SMAHO plug disassembled without damaging it. From the prying marks in the photos I can see you used quite a bit of force. I tried to pull the PCB out with some pliers with little success. prying with a pair of tweezers did not do anything for me as well. Is the PCB glued to the case (heat gun on low might work) or are there solder joints which need to be removed? Your help would be greatly appreciated.

Regards,
Richard

**Comment by Sinclair81** [comment]
No, it doesn't take much force.
You only have to unsolder connection J4 (bottom left) and connection H3 (top right). J4 is a small circuit board and H3 is just a wire.
