### ISSUE TITLE
3Ch or 4Ch Plug

### ISSUE THREAD

**Issue by geomaddin** [Sinclair81/Homebridge-Tasmota-TS#3]
Hi, 

it would be great to switch on more than one relais per socket. I have got a smart power plug from AOFO with 4 sockets and and 1 USB relais. 
The only change to do is to ask for an other parameter like "Relais" and put it behind "Power". 
For example relais 5 (USB) :     TasmotaIP/cm?cmnd=Power5%20Status

The preset should be "1".

Thanks for your work.

**Comment by Sinclair81** [comment]
It should now work with multiple relays.
Create an accessory per relay in the config! And try it out.
Without wearing a number and with relay 1 it works.

**Comment by geomaddin** [comment]
I tried it but it doesn't work for relais 2 till 5. Maybe there is a problem with the answer of the status querry? It is not {"POWER":"ON"} but {"POWER2":"ON"} for example.

**Comment by Sinclair81** [comment]
Hm?
For "Power Off" and / or "Power1 Off", "{" POWER ":" OFF "}" always comes back.
Which version of the plugin are you using?

**Comment by Sinclair81** [comment]
OK, you are right from Relay 2 On, Power2 On also comes back. I will install it in a moment.

**Comment by Sinclair81** [comment]
Please test again!

**Comment by geomaddin** [comment]
Works now, thanks.
