### ISSUE TITLE
ETIMEDOUT

### ISSUE THREAD

**Issue by quorea** [Sinclair81/Homebridge-Tasmota-TS#4]
Hello Sinclair81,

Thanks so much for your ingenuity.

I am getting "ETIMEDOUT" response after installing the plugin to control my gosund dimmer switch. Any help to a novice? Thanks in advance for your help.

**Comment by Sinclair81** [comment]
Hi quorea,
Sorry but this plugin is only for switchable sockets.
And unfortunately I don't have any other devices to test.
